package ArrayList;

adt ArrayList {
    Arraylist  { }
    Add_object        { ArrayList self; Object e; }
    Addb_object       { ArrayList self; Object e; }
    Setb_int_object       { ArrayList self; int i; Object e; }
    Set_int_object        { ArrayList self; int i; Object e; }
    Removeb_int    { ArrayList self; int i; }
    Size       { ArrayList self; }
    Remove_int     { ArrayList self; int i; }
}

Object ArrayList_ArrayList() {
    return new Object(__cid=ArrayList(), _arraylist=new Arraylist());
}

Object add_Object_Object(Object self, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Add_object(self=self._arraylist, e=e));
}

Object addb_Object_Object(Object self, Object e) {
    self._arraylist=new Addb_object(self=self._arraylist, e=e);
return self;
}

Object setb_Object_int_Object(Object self, int i, Object e) {
    self._arraylist=new Setb_int_object(self=self._arraylist, i=i, e=e);
return self;
}

Object set_Object_int_Object(Object self, int i, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Set_int_object(self=self._arraylist, i=i, e=e));
}

Object removeb_Object_int(Object self, int i) {
    self._arraylist=new Removeb_int(self=self._arraylist, i=i);
return self;
}

int size_Object(Object self) {
    return xform_size_ArrayList(self._arraylist);
}

Object remove_Object_int(Object self, int i) {
    return new Object(__cid=ArrayList(), _arraylist=new Remove_int(self=self._arraylist, i=i));
}

int xform_size_ArrayList(ArrayList selff) {
  ArrayList self = selff;
  int i = -1;
  ArrayList inner = null;
  switch(self) {
  case Arraylist: {
    return ??;
    /* return 0; */
  }
  case Add_object: { assert false; }
  case Addb_object: {
    int sz = xform_size_ArrayList(self.self);
    return {| ?? | sz * ?? | sz + ?? | sz - ?? |};
    /* return xform_size_ArrayList(self.self) + 1; */
    /* i = 0; */
    /* inner = self.self; */
  }
  case Setb_int_object: {
    int sz = xform_size_ArrayList(self.self);
    return {| ?? | sz * ?? | sz + ?? | sz - ?? |};
    /* return xform_size_ArrayList(self.self); */
    /* i = 1; */
    /* inner = self.self;     */
  }
  case Set_int_object: { assert false; }
  case Removeb_int: {
    int sz = xform_size_ArrayList(self.self);
    return {| ?? | sz * ?? | sz + ?? | sz - ?? |};
    /* return xform_size_ArrayList(self.self) - 1; */
    /* i = 2; */
    /* inner = self.self;     */
  }
  case Size: { assert false; }
  case Remove_int: { assert false; }
  }

  /* if (i >= 0) { */
  /*   int sz = xform_size_ArrayList(inner); */
  /*   if (i == 0) { */
  /*     return sz + 1; */
  /*   } else if (i == 1) { */
  /*     return sz; */
  /*   } else if (i == 2) { */
  /*     return sz - 1; */
  /*   } */
  /* } */
  
  return 0;
}
