package meta;

// distinct class IDs
int ArrayList()      { return 11; }
int Assert()         { return 10; }
int Boolean()        { return 8; }
int Bucketing()      { return 2; }
int BucketingTest()  { return 3; }
int CharSequence()   { return 7; }
int Character()      { return 12; }
int HashTable()      { return 4; }
int Integer()        { return 9; }
int Object()         { return 1; }
int Pair()           { return 5; }
int String()         { return 6; }

// Uninterpreted functions
