package t2;

// pop(push(push(push(push(push(push(s, o1), o2), o3), o4), o5), o6)) == 
//     (push(push(push(push(push(s, o1), o2), o3), o4), o5), o6)
// pop(push(push(push(push(push(push(s, o1), o2), o3), o4), o5), o6)) == 
//     (pop(push(push(push(push(push(push(s, o1), o2), o3), o4), o5), o6)), o6)
harness void mn() {
  Object s = object();
  Object o1 = object();
  Object o2 = object();
  Object o3 = object();
  Object o4 = object();
  Object o5 = object();
  Object o6 = object();

  Object psh1 = push(s, o1);
  Object psh12 = push(psh1, o2);
  Object psh123 = push(psh12, o3);
  Object psh1234 = push(psh123, o4);
  Object psh12345 = push(psh1234, o5);
  Object psh123456 = push(psh12345, o6);

  Object poppsh123456 = pop(psh123456);

  assert equals_Axiom(elem(xform(tuple(poppsh123456, null),??)), o6);
  assert equals_Axiom(stack(xform(tuple(poppsh123456, null),??)), psh12345);
  assert equals_Axiom(stack(xform(tuple(poppsh123456, null),??)), poppsh123456);
}
