package t4;

// pop(pop(push(push(s, o1), o2))) == o1
harness void mn() {
  Object s = object();
  Object o1 = object();
  Object o2 = object();

  Object psh1 = push(s, o1);
  Object psh12 = push(psh1, o2);

  Object poppsh12 = pop(psh12);
  Object poppoppsh12 = pop(poppsh12);

  assert equals_Axiom(elem(xform(tuple(poppoppsh12, null), ??)), o1);
  assert equals_Axiom(stack(xform(tuple(poppoppsh12, null), ??)), s);
  assert equals_Axiom(stack(xform(tuple(poppoppsh12, null), ??)), poppoppsh12);
}
