package JCECipher;

Object JCECipher_JCECipher(Object self) {
    return self;
}

Object JCECipher_JCECipher_String_String_String(Object self, Object provider, Object algorithm, Object transformation) {
  self.provider_JCECipher = provider;
  self.algorithm_JCECipher = algorithm;
  self.transformation_JCECipher = transformation;
  return self;
}

Object getCipher_boolean_SecretKeySpec_byte(Object self, Object isEncryption, Object key, Object IV) {
  Object cipher;
  cipher = getInstance_String_String@Cipher(self.transformation_JCECipher, self.provider_JCECipher);
  Object keyValue = SecretKeySpec_SecretKeySpec();
  Object IVspec = IvParameterSpec_IvParameterSpec_byte(new Object(__cid=IvParameterSpec()), IV);
  if (isEncryption._bit) {
    if (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int) { init_Object_int_SecretKeySpec_AlgorithmParameterSpec@Cipher(cipher, (new Object(__cid=-2, _int=??)), keyValue, IVspec); }
    else { 0; }; cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? initb_Object_int_SecretKeySpec_AlgorithmParameterSpec@Cipher(cipher, (new Object(__cid=-2, _int=??)), keyValue, IVspec) : null);
  }
  else {
    if (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int) { init_Object_int_SecretKeySpec_AlgorithmParameterSpec@Cipher(cipher, (new Object(__cid=-2, _int=??)), keyValue, IVspec); }
    else { 0; }; cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? initb_Object_int_SecretKeySpec_AlgorithmParameterSpec@Cipher(cipher, (new Object(__cid=-2, _int=??)), keyValue, IVspec) : null);
  }
  return cipher;
}

Object encrypt_byte_SecretKeySpec_byte(Object self, Object data, Object key, Object IV) {
  return translate_boolean_byte_SecretKeySpec_byte@JCECipher(self, (new Object(__cid=-4, _bit=true)), data, key, IV);
}

Object decrypt_byte_SecretKeySpec_byte(Object self, Object data, Object key, Object IV) {
  return translate_boolean_byte_SecretKeySpec_byte@JCECipher(self, (new Object(__cid=-4, _bit=false)), data, key, IV);
}

generator Object genCipherText_byte_boolean_SecretKeySpec_byte(Object self, Object data, Object isEncryption, Object key, Object IV) {
  Object cipherText;
  Object updateBytes = (new Object(__cid=-2, _int=0));
  Object finalBytes = (new Object(__cid=-2, _int=0));
  Object cipher;

  if (??) {
    cipher = getCipher_boolean_SecretKeySpec_byte@JCECipher(self, isEncryption, key, IV);
  }
  if (??) {
    updateBytes = xform_update_Cipher_byte_int_int_byte_int(cipher._cipher, data, (new Object(__cid=-2, _int=??)), new Object(__cid=-2, _int=??), cipherText, (new Object(__cid=-2, _int=??)));
    cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? updateb_Object_byte_int_int_byte_int@Cipher(cipher, data, (new Object(__cid=-2, _int=??)), new Object(__cid=-2, _int=??), cipherText, (new Object(__cid=-2, _int=??))) : null);
  }
  if (??) {
    finalBytes = xform_doFinale_Cipher_byte_int_int_byte_int(cipher._cipher, data, (new Object(__cid=-2, _int=??)), (new Object(__cid=-2, _int=??)), cipherText, updateBytes);
    cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinaleb_Object_byte_int_int_byte_int@Cipher(cipher, data, (new Object(__cid=-2, _int=??)), (new Object(__cid=-2, _int=??)), cipherText, updateBytes) : null);
  }
  if (??) {
    if (isEncryption._bit) {
      cipherText = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinal_Object_Object@Cipher(cipher, data) : null);
      cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinalb_Object_Object@Cipher(cipher, data) : null);
    } else {
      cipherText = xform_doFinal_Cipher_Object(cipher._cipher, data);
      cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinalb_Object_Object@Cipher(cipher, data) : null);
    }
  }
  if (??) {
    if (!isEncryption._bit) {
      if (updateBytes._int + finalBytes._int < cipherText._array_char.length._int) {
	cipherText = copyOf_byte_int@Arrays(cipherText, (new Object(__cid=-2, _int=updateBytes._int + finalBytes._int)));
      }
    }
  }
  if (??) {
    cipherText = genCipherText_byte_boolean_SecretKeySpec_byte@JCECipher(self, cipherText, isEncryption, key, IV);
  }
  
  return cipherText;
}

Object translate_boolean_byte_SecretKeySpec_byte(Object self, Object isEncryption, Object data, Object key, Object IV) {
  /* Object cipherText; */
  /* Object updateBytes = (new Object(__cid=-2, _int=0)); */
  /* Object finalBytes = (new Object(__cid=-2, _int=0)); */
  /* Object cipher; */

  /* cipher = getCipher_boolean_SecretKeySpec_byte@JCECipher(self, isEncryption, key, IV); */
  /* updateBytes = xform_update_Cipher_byte_int_int_byte_int(cipher._cipher, data, (new Object(__cid=-2, _int=??)), new Object(__cid=-2, _int=??), cipherText, (new Object(__cid=-2, _int=??))); */
  /* cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? updateb_Object_byte_int_int_byte_int@Cipher(cipher, data, (new Object(__cid=-2, _int=??)), new Object(__cid=-2, _int=??), cipherText, (new Object(__cid=-2, _int=??))) : null); */
  /* finalBytes = xform_doFinale_Cipher_byte_int_int_byte_int(cipher._cipher, data, (new Object(__cid=-2, _int=??)), (new Object(__cid=-2, _int=??)), cipherText, updateBytes); */
  /* cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinaleb_Object_byte_int_int_byte_int@Cipher(cipher, data, (new Object(__cid=-2, _int=??)), (new Object(__cid=-2, _int=??)), cipherText, updateBytes) : null); */
  /* if (isEncryption._bit) { */
  /*   cipherText = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinal_Object_Object@Cipher(cipher, data) : null); */
  /*   cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinalb_Object_Object@Cipher(cipher, data) : null); */
  /* } else { */
  /*   cipherText = xform_doFinal_Cipher_Object(cipher._cipher, data); */
  /*   cipher = (cipher.__cid == (new Object(__cid=-2, _int=Cipher()))._int ? doFinalb_Object_Object@Cipher(cipher, data) : null); */
  /* } */
  /* if (!isEncryption._bit) { */
  /*   if (updateBytes._int + finalBytes._int < cipherText._array_char.length._int) { */
  /*     cipherText = copyOf_byte_int@Arrays(cipherText, (new Object(__cid=-2, _int=updateBytes._int + finalBytes._int))); */
  /*   } */
  /* } */
  /* return cipherText; */
  return genCipherText_byte_boolean_SecretKeySpec_byte@JCECipher(self, data, isEncryption, key, IV);
}

