package SecretKeySpec;

adt SecretKeySpec {
    Secretkeyspec  { }
    Getencoded     { SecretKeySpec self; }
    Equals_object         { SecretKeySpec self; Object o; }
}

Object SecretKeySpec_SecretKeySpec() {
    return new Object(__cid=SecretKeySpec(), _secretkeyspec=new Secretkeyspec());
}

Object getEncoded_Object(Object self) {
    return new Object(__cid=SecretKeySpec(), _secretkeyspec=new Getencoded(self=self._secretkeyspec));
}

Object equals_Object_Object(Object self, Object o) {
    return new Object(__cid=SecretKeySpec(), _secretkeyspec=new Equals_object(self=self._secretkeyspec, o=o));
}

Object xform_SecretKeySpec(SecretKeySpec self) {
  switch(self) {
  case Secretkeyspec: {
    return xform_secretkeyspec_SecretKeySpec(self);
  }
  case Getencoded: {
    return xform_getEncoded_SecretKeySpec(self.self);
  }
  case Equals_object: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  }

  return null;
}
Object xform_equals_SecretKeySpec_Object(SecretKeySpec self, Object o) {
  switch(self) {
  case Secretkeyspec: {
    {
      SecretKeySpec o_o;
      o_o = o._secretkeyspec;
      switch(o_o) {
      case Secretkeyspec: {
        {
	  return (new Object(__cid=-4, _bit=true));
	  /* SecretKeySpec o_o_o; */
          /* o_o_o = o_o.str._cipher; */
          /* switch(o_o_o) { */
          /* case Secretkeyspec: { */

          /* } */
          /* case Getencoded: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); } */
          /* case Equals_object: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); } */
          /* } */

        }
      }
      case Getencoded: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
      case Equals_object: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
      }

    }
  }
  case Getencoded: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  case Equals_object: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  }

  return null;
}
Object xform_getEncoded_SecretKeySpec(SecretKeySpec self) {
  switch(self) {
  case Secretkeyspec: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  case Getencoded: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  case Equals_object: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  }

  return null;
}
Object xform_secretkeyspec_SecretKeySpec(SecretKeySpec self) {
  switch(self) {
  case Secretkeyspec: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  case Getencoded: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  case Equals_object: { return new Object(__cid=SecretKeySpec(), _secretkeyspec=self); }
  }

  return null;
}
