package t0;

// len(concat(s1,s2)) == len(s1) + len(s2)
harness void mn() {
  Object s1 = string(String(), 8, "hello, ");
  Object s2 = string(String(), 7, "world!");

  Object len1 = (s1.__cid == String() || s1.__cid == Concat() ? length(s1) : null);
  Object len2 = (s2.__cid == String() || s2.__cid == Concat() ? length(s2) : null);
  
  // WHY DOES THIS MAKE IT TAKE SO MUCH LONGER??
  // Object len1 = (s1.__cid == String() || s1.__cid == Concat() ? Len_Len_Object(new Object(__cid=Len()), s1) : null);
  // Object len2 = (s2.__cid == String() || s2.__cid == Concat() ? Len_Len_Object(new Object(__cid=Len()), s2) : null);

  Object len12 = plus(len1, len2);

  Object c12 = (s1.__cid == String() || s1.__cid == Concat() ?  concat(s1, s2): null);
  Object lenc12 = (c12.__cid == String() || c12.__cid == Concat() ? length(c12) : null);

  // WHY DOES THIS MAKE IT TAKE SO MUCH LONGER??
  // Object c12 = (s1.__cid == String() || s1.__cid == Concat() ?  Concat_Concat_Object_Object(new Object(__cid=Concat()), s1, s2): null);
  // Object lenc12 = (c12.__cid == String() || c12.__cid == Concat() ? Len_Len_Object(new Object(__cid=Len()), c12) : null);

  assert equals_Axiom(xform(lenc12,??), len12);
}
