package t3;

// len(concat(s1,s2)) + len(concat(s3,s4) + len(concat(s5,s6))) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6)
harness void mn() {
  Object s1 = string(String(), 8, "hello, ");
  Object s2 = string(String(), 7, "world!");
  Object s3 = string(String(), 14, "ALLWORKNOPLAY");
  Object s4 = string(String(), 20, "MAKESJACKADULLBOY!!");
  Object s5 = string(String(), 23, "itwasthe best of times");
  Object s6 = string(String(), 26, "it was the worst of times");
  Object s7 = string(String(), 23, "itwasthe best of times");
  Object s8 = string(String(), 26, "it was the worst of times");

  Object len1 = (s1.__cid == String() || s1.__cid == Concat() ? length(s1) : null);
  Object len2 = (s2.__cid == String() || s2.__cid == Concat() ? length(s2) : null);
  Object len3 = (s3.__cid == String() || s3.__cid == Concat() ? length(s3) : null);
  Object len4 = (s4.__cid == String() || s4.__cid == Concat() ? length(s4) : null);
  Object len5 = (s5.__cid == String() || s5.__cid == Concat() ? length(s5) : null);
  Object len6 = (s6.__cid == String() || s6.__cid == Concat() ? length(s6) : null);
  Object len7 = (s7.__cid == String() || s7.__cid == Concat() ? length(s7) : null);
  Object len8 = (s8.__cid == String() || s8.__cid == Concat() ? length(s8) : null);

  Object len12345678 = plus(plus(plus(len1, len2), plus(len3, len4)), plus(plus(len5, len6), plus(len7, len8)));

  Object c12 = (s1.__cid == String() || s1.__cid == Concat() ? concat(s1, s2) : null);
  Object c34 = (s3.__cid == String() || s3.__cid == Concat() ? concat(s3, s4) : null);
  Object c56 = (s5.__cid == String() || s5.__cid == Concat() ? concat(s5, s6) : null);
  Object c78 = (s7.__cid == String() || s7.__cid == Concat() ? concat(s7, s8) : null);

  Object lenc12 = (c12.__cid == String() || c12.__cid == Concat() ? length(c12) : null);
  Object lenc34 = (c34.__cid == String() || c34.__cid == Concat() ? length(c34) : null);
  Object lenc56 = (c56.__cid == String() || c56.__cid == Concat() ? length(c56) : null);
  Object lenc78 = (c78.__cid == String() || c78.__cid == Concat() ? length(c78) : null);

  Object lenc12c34c56c78 = plus(plus(lenc12, lenc34), plus(lenc56, lenc78));

  assert equals_Axiom(xform(lenc12c34c56c78, ??), len12345678);
}
