package t4;

// len(concat(concat(s1,s2),s3)) == len(s1) + len(s2) + len(s3)
harness void mn() {
  Object s1 = string(String(), 8, "hello, ");
  Object s2 = string(String(), 7, "world!");
  Object s3 = string(String(), 14, "ALLWORKNOPLAY");
 
  Object len1 = (s1.__cid == String() || s1.__cid == Concat() ? length(s1) : null);
  Object len2 = (s2.__cid == String() || s2.__cid == Concat() ? length(s2) : null);
  Object len3 = (s3.__cid == String() || s3.__cid == Concat() ? length(s3) : null);

  Object len123 = plus(plus(len1, len2), len3);

  Object c12 = (s1.__cid == String() || s1.__cid == Concat() ? concat(s1, s2) : null);

  Object cc123 = (c12.__cid == String() || c12.__cid == Concat() ? concat(c12, s3) : null);
  Object lencc12 = (s3.__cid == String() || s3.__cid == Concat() ? length(cc123) : null);

  assert equals_Axiom(xform(lencc12, ??), len123);
}
