package Object;

Object Object_Object(Object self) {
    return self;
}

Object equals_Object_Object(Object a, Object b) {
  if (a == null) {
    if (b == null) {
      return (new Object(__cid=-4, _bit=true));
    }
    return (new Object(__cid=-4, _bit=false));
  }
  return (a.__cid == (new Object(__cid=-2, _int=HashTable()))._int ? equals_Object@Object(a, b) : a.__cid == (new Object(__cid=-2, _int=Boolean()))._int ? equals_Object@Object(a, b) : a.__cid == (new Object(__cid=-2, _int=Integer()))._int ? equals_Object@Integer(a, b) : a.__cid == (new Object(__cid=-2, _int=Character()))._int ? equals_Object@Character(a, b) : a.__cid == (new Object(__cid=-2, _int=String()))._int ? equals_Object@String(a, b) : a.__cid == (new Object(__cid=-2, _int=HashTableTest()))._int ? equals_Object@Object(a, b) : a.__cid == (new Object(__cid=-2, _int=HashTableNode()))._int ? equals_Object@Object(a, b) : a.__cid == (new Object(__cid=-2, _int=Assert()))._int ? equals_Object@Object(a, b) : a.__cid == (new Object(__cid=-2, _int=ArrayList()))._int ? equals_Object@Object(a, b) : a.__cid == (new Object(__cid=-2, _int=Object()))._int ? equals_Object@Object(a, b) : null);
}

Object equals_Object(Object self, Object obj) {
  return (new Object(__cid=-4, _bit=self == obj));
}

Object hashCode(Object self) {
  return (new Object(__cid=-2, _int=0));
}

struct Object {
  int           __cid;
  Object        key_HashTableNode;
  Object        value_HashTableNode;
  Object        next_HashTableNode;
  Object        classUnderTest_HashTableTest;
  Object        _value_String;
  Object        _count_String;
  Object        value_Character;
  Object        value_Integer;
  Object        bool_Boolean;
  Object        maxLoadFactor_HashTable;
  Object        capacityGrowth_HashTable;
  Object        initialCapacity_HashTable;
  Object        size_HashTable;
  Object        currentCapacity_HashTable;
  Object        buckets_HashTable;
  ArrayList     _arraylist;
  Array_bit     _array_bit;
  Array_char    _array_char;
  Array_int     _array_int;
  Array_float   _array_float;
  Array_double  _array_double;
  Array_Object  _array_object;
  bit           _bit;
  char          _char;
  int           _int;
  float         _float;
  double        _double;
}
