package Objects;

Object Objects_Objects(Object self) {
    return self;
}

bit equals_Object_Object(Object a, Object b) {
  if (a == null) {
    if (b == null) {
      return true;
    }
    return false;
  }
  return (a.__cid == Float() ? equals_Object@Float(a, b) : a.__cid == HashMap() ? equals_Object@Object(a, b) : a.__cid == String() ? equals_Object@String(a, b) : a.__cid == Number() ? equals_Object@Object(a, b) : a.__cid == HashMap_Simple() ? equals_Object@Object(a, b) : a.__cid == HashMap_Simple_Node() ? equals_Object@Object(a, b) : a.__cid == HashMap_TreeNode() ? equals_Object@Object(a, b) : a.__cid == ArrayList() ? equals_Object@Object(a, b) : a.__cid == Integer() ? equals_Object@Integer(a, b) : a.__cid == Objects() ? equals_Object@Object(a, b) : a.__cid == HashMap_Node() ? equals_Object@Object(a, b) : a.__cid == Object() ? equals_Object@Object(a, b) : 0);
}

int hashCode_Object(Object o) {
  return o != null ? (o.__cid == Float() ? hashCode@Object(o) : o.__cid == HashMap() ? hashCode@Object(o) : o.__cid == String() ? hashCode@Object(o) : o.__cid == Number() ? hashCode@Object(o) : o.__cid == HashMap_Simple() ? hashCode@Object(o) : o.__cid == HashMap_Simple_Node() ? hashCode@Object(o) : o.__cid == HashMap_TreeNode() ? hashCode@Object(o) : o.__cid == ArrayList() ? hashCode@Object(o) : o.__cid == Integer() ? hashCode@Integer(o) : o.__cid == Objects() ? hashCode@Object(o) : o.__cid == HashMap_Node() ? hashCode@Object(o) : o.__cid == Object() ? hashCode@Object(o) : 0) : 0;
}

