package PasswordMap;

Object PasswordMap_PasswordMap(Object self) {
  self.passMap_PasswordMap = HashMap_HashMap();
  self.masterHash_PasswordMap = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=15+1, A="Secret Password"), 0, 15);
  return self;
}

void add_String_String(Object self, Object tag, Object passEncryption) {
  self.passMap_PasswordMap = (self.passMap_PasswordMap.__cid == HashMap() ? putb_Object_Object_Object@HashMap(self.passMap_PasswordMap, tag, passEncryption) : null);
}

void remove_String(Object self, Object tag) {
  boolean cont = booleanValue@Boolean(xform_containsKey_HashMap_Object(self.passMap_PasswordMap._hashmap, tag));
  if (cont) self.passMap_PasswordMap = (self.passMap_PasswordMap.__cid == HashMap() ? removeb_Object_Object@HashMap(self.passMap_PasswordMap, tag) : null);
}

Object get_String(Object self, Object domainHash) {
  return xform_get_HashMap_Object(self.passMap_PasswordMap._hashmap, domainHash);
  /* return (self.passMap_PasswordMap.__cid == HashMap() ? get_Object_Object@HashMap(self.passMap_PasswordMap, domainHash) : null); */
}

