package Boolean;

Object Boolean_Boolean(Object self) {
    return self;
}

Object Boolean_Boolean_boolean(Object self, Object bool) {
  self.bool_Boolean = bool;
  return self;
}

Object booleanValue(Object self) {
  return self.bool_Boolean;
}

Object toString(Object self) {
  return toString_boolean(self.bool_Boolean);
}

Object toString_boolean(Object bool) {
  if (bool._bit) return String_String_char_int_int(new Object(__cid=String()), Wrap_Array_char(new Array_char(length=new Object(__cid=-2, _int=4+1), A="true")), new Object(__cid=-2, _int=0), new Object(__cid=-2, _int=4));
  return String_String_char_int_int(new Object(__cid=String()), Wrap_Array_char(new Array_char(length=new Object(__cid=-2, _int=5+1), A="false")), new Object(__cid=-2, _int=0), new Object(__cid=-2, _int=5));
}

