package HashMap_Simple;

int DEFAULT_INITIAL_CAPACITY = 1 << 4;
int DEFAULT_INITIAL_CAPACITY_g() { return DEFAULT_INITIAL_CAPACITY; }
void DEFAULT_INITIAL_CAPACITY_s(int DEFAULT_INITIAL_CAPACITY_s) { DEFAULT_INITIAL_CAPACITY = DEFAULT_INITIAL_CAPACITY_s; }

Object HashMap_Simple_HashMap_Simple(Object self) {
  self.elementData_HashMap_Simple = new Array_Object(length=DEFAULT_INITIAL_CAPACITY);
  self.numPairs_HashMap_Simple = 0;
  self.capacity_HashMap_Simple = DEFAULT_INITIAL_CAPACITY;
  return self;
}

int size(Object self) {
  return self.numPairs_HashMap_Simple;
}

bit isEmpty(Object self) {
  return self.numPairs_HashMap_Simple == 0;
}

void resize_int(Object self, int newSize) {
  int i,  h,  hashMod;
  Object n;
  Array_Object oldElementData = self.elementData_HashMap_Simple;
  Array_Object newElementData = new Array_Object(length=newSize);
  Object k;
  Object v;
  for (i = 0; i < self.capacity_HashMap_Simple; i++) {
    if (oldElementData.A[i] != null) {
      h = oldElementData.A[i].hash_HashMap_Simple_Node;
      k = oldElementData.A[i].key_HashMap_Simple_Node;
      v = oldElementData.A[i].value_HashMap_Simple_Node;
      hashMod = h % newSize;
      if (hashMod < 0) {
        hashMod = hashMod + newSize;
      }
      newElementData.A[hashMod] = HashMap_Simple_Node_HashMap_Simple_Node_HashMap_Simple_K_V_int(new Object(__cid=HashMap_Simple_Node()), self, k, v, h);
    }
  }
  self.elementData_HashMap_Simple = newElementData;
  self.capacity_HashMap_Simple = newSize;
}

bit containsValue_V(Object self, Object value) {
  int i;
  for (i = 0; i < self.capacity_HashMap_Simple; i++) {
    if (self.elementData_HashMap_Simple.A[i] != null) {
      Object v = self.elementData_HashMap_Simple.A[i].value_HashMap_Simple_Node;
      if ((value.__cid == Character() ? equals_Object@Object(value, v) : value.__cid == Number() ? equals_Object@Object(value, v) : value.__cid == HashMap_Simple() ? equals_Object@Object(value, v) : value.__cid == Integer() ? equals_Object@Integer(value, v) : value.__cid == String() ? equals_Object@String(value, v) : value.__cid == HashMap_Simple_Node() ? equals_Object@Object(value, v) : value.__cid == FreqTable() ? equals_Object@Object(value, v) : value.__cid == ArrayList() ? equals_Object@Object(value, v) : value.__cid == Object() ? equals_Object@Object(value, v) : 0)) {
        return true;
      }
    }
  }
  return false;
}

bit containsKey_K(Object self, Object key) {
  return get_K@HashMap_Simple(self, key) != null;
}

Object get_K(Object self, Object key) {
  int hashMod = (key.__cid == Character() ? hashCode@Object(key) : key.__cid == Number() ? hashCode@Object(key) : key.__cid == HashMap_Simple() ? hashCode@Object(key) : key.__cid == Integer() ? hashCode@Integer(key) : key.__cid == String() ? hashCode@String(key) : key.__cid == HashMap_Simple_Node() ? hashCode@Object(key) : key.__cid == FreqTable() ? hashCode@Object(key) : key.__cid == ArrayList() ? hashCode@Object(key) : key.__cid == Object() ? hashCode@Object(key) : 0) % self.capacity_HashMap_Simple;
  if (hashMod < 0) {
    hashMod = hashMod + self.capacity_HashMap_Simple;
  }
  Object node = self.elementData_HashMap_Simple.A[hashMod];
  if (node != null) {
    if ((key.__cid == Character() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Number() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == HashMap_Simple() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Integer() ? equals_Object@Integer(key, node.key_HashMap_Simple_Node) : key.__cid == String() ? equals_Object@String(key, node.key_HashMap_Simple_Node) : key.__cid == HashMap_Simple_Node() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == FreqTable() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == ArrayList() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Object() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : 0)) {
      return node.value_HashMap_Simple_Node;
    }
  }
  return null;
}

void clear(Object self) {
  self.elementData_HashMap_Simple = new Array_Object(length=DEFAULT_INITIAL_CAPACITY);
  self.capacity_HashMap_Simple = DEFAULT_INITIAL_CAPACITY;
  self.numPairs_HashMap_Simple = 0;
}

Object remove_K(Object self, Object key) {
  Object val = get_K@HashMap_Simple(self, key);
  int hashMod = (key.__cid == Character() ? hashCode@Object(key) : key.__cid == Number() ? hashCode@Object(key) : key.__cid == HashMap_Simple() ? hashCode@Object(key) : key.__cid == Integer() ? hashCode@Integer(key) : key.__cid == String() ? hashCode@String(key) : key.__cid == HashMap_Simple_Node() ? hashCode@Object(key) : key.__cid == FreqTable() ? hashCode@Object(key) : key.__cid == ArrayList() ? hashCode@Object(key) : key.__cid == Object() ? hashCode@Object(key) : 0) % self.capacity_HashMap_Simple;
  if (hashMod < 0) {
    hashMod = hashMod + self.capacity_HashMap_Simple;
  }
  self.elementData_HashMap_Simple.A[hashMod] = null;
  if (val != null) {
    self.numPairs_HashMap_Simple--;
  }
  return val;
}

Object put_K_V(Object self, Object key, Object value) {
  int h = (key.__cid == Character() ? hashCode@Object(key) : key.__cid == Number() ? hashCode@Object(key) : key.__cid == HashMap_Simple() ? hashCode@Object(key) : key.__cid == Integer() ? hashCode@Integer(key) : key.__cid == String() ? hashCode@String(key) : key.__cid == HashMap_Simple_Node() ? hashCode@Object(key) : key.__cid == FreqTable() ? hashCode@Object(key) : key.__cid == ArrayList() ? hashCode@Object(key) : key.__cid == Object() ? hashCode@Object(key) : 0);
  return putVal_int_K_V@HashMap_Simple(self, h, key, value);
}

Object replace_K_V(Object self, Object key, Object newVal) {
  int hashMod = (key.__cid == Character() ? hashCode@Object(key) : key.__cid == Number() ? hashCode@Object(key) : key.__cid == HashMap_Simple() ? hashCode@Object(key) : key.__cid == Integer() ? hashCode@Integer(key) : key.__cid == String() ? hashCode@String(key) : key.__cid == HashMap_Simple_Node() ? hashCode@Object(key) : key.__cid == FreqTable() ? hashCode@Object(key) : key.__cid == ArrayList() ? hashCode@Object(key) : key.__cid == Object() ? hashCode@Object(key) : 0) % self.capacity_HashMap_Simple;
  if (hashMod < 0) {
    hashMod = hashMod + self.capacity_HashMap_Simple;
  }
  Object node = self.elementData_HashMap_Simple.A[hashMod];
  if (node != null) {
    if ((key.__cid == Character() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Number() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == HashMap_Simple() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Integer() ? equals_Object@Integer(key, node.key_HashMap_Simple_Node) : key.__cid == String() ? equals_Object@String(key, node.key_HashMap_Simple_Node) : key.__cid == HashMap_Simple_Node() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == FreqTable() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == ArrayList() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Object() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : 0)) {
      node.value_HashMap_Simple_Node = newVal;
      return node.value_HashMap_Simple_Node;
    }
  }
  return null;
}

Object putVal_int_K_V(Object self, int hash, Object key, Object value) {
  int hashMod = hash % self.capacity_HashMap_Simple;
  if (hashMod < 0) {
    hashMod = hashMod + self.capacity_HashMap_Simple;
  }
  Object node = self.elementData_HashMap_Simple.A[hashMod];
  if (node != null) {
    if (node.hash_HashMap_Simple_Node != hash || !(key.__cid == Character() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Number() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == HashMap_Simple() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Integer() ? equals_Object@Integer(key, node.key_HashMap_Simple_Node) : key.__cid == String() ? equals_Object@String(key, node.key_HashMap_Simple_Node) : key.__cid == HashMap_Simple_Node() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == FreqTable() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == ArrayList() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : key.__cid == Object() ? equals_Object@Object(key, node.key_HashMap_Simple_Node) : 0)) {
      resize_int@HashMap_Simple(self, hash + 1);
      hashMod = hash % self.capacity_HashMap_Simple;
      if (hashMod < 0) {
        hashMod = hashMod + self.capacity_HashMap_Simple;
      }
      node = self.elementData_HashMap_Simple.A[hashMod];
      self.numPairs_HashMap_Simple++;
    }
    self.elementData_HashMap_Simple.A[hashMod] = HashMap_Simple_Node_HashMap_Simple_Node_HashMap_Simple_K_V_int(new Object(__cid=HashMap_Simple_Node()), self, key, value, hash);
    if (node != null) {
      return node.value_HashMap_Simple_Node;
    }
    else {
      return null;
    }
  }
  self.elementData_HashMap_Simple.A[hashMod] = HashMap_Simple_Node_HashMap_Simple_Node_HashMap_Simple_K_V_int(new Object(__cid=HashMap_Simple_Node()), self, key, value, hash);
  self.numPairs_HashMap_Simple++;
  return null;
}

void putValNoResize_int_K_V(Object self, int hash, Object key, Object value) {
  int hashMod = hash % self.capacity_HashMap_Simple;
  if (hashMod < 0) {
    hashMod = hashMod + self.capacity_HashMap_Simple;
  }
  self.elementData_HashMap_Simple.A[hashMod] = HashMap_Simple_Node_HashMap_Simple_Node_HashMap_Simple_K_V_int(new Object(__cid=HashMap_Simple_Node()), self, key, value, hash);
}

