package meta;

// distinct class IDs
int Integer()        { return 3; }
int Object()         { return 1; }
int TreeSet()        { return 4; }
int TreeSetTester()  { return 2; }
int Array()          { return -1; }
int _int()           { return -2; }
int _char()          { return -3; }
int _bit()           { return -4; }
int _float()         { return -5; }
int _double()        { return -6; }

// Uninterpreted functions
