package ArrayList;

adt ArrayList {
    Arraylist       { }
    Add_e             { ArrayList self; Object e; }
    Addb_e            { ArrayList self; Object e; }
    Get_int             { ArrayList self; int i; }
    Setb_int_e            { ArrayList self; int i; Object e; }
    Set_int_e             { ArrayList self; int i; Object e; }
    Ensurecapacity_int  { ArrayList self; int n; }
    Size            { ArrayList self; }
}

Object ArrayList_ArrayList() {
    return new Object(__cid=ArrayList(), _arraylist=new Arraylist());
}

Object add_Object_E(Object self, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Add_e(self=self._arraylist, e=e));
}

Object addb_Object_E(Object self, Object e) {
    self._arraylist=new Addb_e(self=self._arraylist, e=e);
return self;
}

Object get_Object_int(Object self, int i) {
    return xform_get_ArrayList_int(self._arraylist, i);
}

Object setb_Object_int_E(Object self, int i, Object e) {
    self._arraylist=new Setb_int_e(self=self._arraylist, i=i, e=e);
return self;
}

Object set_Object_int_E(Object self, int i, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Set_int_e(self=self._arraylist, i=i, e=e));
}

Object ensureCapacity_Object_int(Object self, int n) {
    return new Object(__cid=ArrayList(), _arraylist=new Ensurecapacity_int(self=self._arraylist, n=n));
}

int size_Object(Object self) {
    return xform_size_ArrayList(self._arraylist);
}

Object xform_addb_ArrayList_E(ArrayList selff, Object e) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: { assert false; }
  case Add_e: { assert false; }
  case Addb_e: { assert false; }
  case Get_int: { assert false; }
  case Setb_int_e: { assert false; }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return null;
}
int xform_size_ArrayList(ArrayList selff) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: {
    /* return 0; */
    return ??;
  }
  case Add_e: { assert false; }
  case Addb_e: {
    int sz = xform_size_ArrayList(self.self);
    return {| ?? | sz * ?? | sz + ?? | sz - ?? | sz / ?? |};
    /* return xform_size_ArrayList(self.self) + 1; */
  }
  case Get_int: { assert false; }
  case Setb_int_e: {
    int sz = xform_size_ArrayList(self.self);
    return {| ?? | sz * ?? | sz + ?? | sz - ?? | sz / ?? |};
    /* return xform_size_ArrayList(self.self); */
  }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return 0;
}
Object xform_get_ArrayList_int(ArrayList selff, int i) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: { assert false; }
  case Add_e: { assert false; }
  case Addb_e: {
    return (xform_size_ArrayList(self.self) == i ? self.e : xform_get_ArrayList_int(self.self, i));
  }
  case Get_int: { assert false; }
  case Setb_int_e: {
    return (i == self.i ? self.e : xform_get_ArrayList_int(self.self, i));
  }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return null;
}
Object xform_add_ArrayList_E(ArrayList selff, Object e) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: { assert false; }
  case Add_e: { assert false; }
  case Addb_e: { assert false; }
  case Get_int: { assert false; }
  case Setb_int_e: { assert false; }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return null;
}
Object xform_setb_ArrayList_int_E(ArrayList selff, int i, Object e) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: { assert false; }
  case Add_e: { assert false; }
  case Addb_e: { assert false; }
  case Get_int: { assert false; }
  case Setb_int_e: { assert false; }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return null;
}
void xform_ensureCapacity_ArrayList_int(ArrayList selff, int n) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: { assert false; }
  case Add_e: { assert false; }
  case Addb_e: { assert false; }
  case Get_int: { assert false; }
  case Setb_int_e: { assert false; }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return;
}
Object xform_set_ArrayList_int_E(ArrayList selff, int i, Object e) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: { assert false; }
  case Add_e: { assert false; }
  case Addb_e: { assert false; }
  case Get_int: { assert false; }
  case Setb_int_e: { assert false; }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return null;
}
Object xform_arraylist_ArrayList(ArrayList selff) {
  ArrayList self = selff;
  switch(self) {
  case Arraylist: { assert false; }
  case Add_e: { assert false; }
  case Addb_e: { assert false; }
  case Get_int: { assert false; }
  case Setb_int_e: { assert false; }
  case Set_int_e: { assert false; }
  case Ensurecapacity_int: { assert false; }
  case Size: { assert false; }
  }

  return null;
}
