package simple_hash;

Object simple_hash_simple_hash(Object self) {
  self.size_simple_hash = 10;
  self.numElements_simple_hash = 0;
  return self;
}

void rehashng(Object self) {
  Object temp1 = ArrayList_ArrayList(new Object(__cid=ArrayList()));
  self.size_simple_hash = self.size_simple_hash * 10;
  for (int i = 0; i < (temp1.__cid == ArrayList() ? size@ArrayList(temp1) : 0); i++) {
    put_int_int@simple_hash(self, 0, 0);
  }
}

void put_int_int(Object self, int i, int j) {
  self.numElements_simple_hash++;
  double rehash = (double)self.numElements_simple_hash / (double)self.size_simple_hash;
  if (rehash > 0.75) rehashng@simple_hash(self);
}

