package meta;

// distinct class IDs
int CharSequence()  { return 4; }
int Object()        { return 1; }
int Stack()         { return 5; }
int String()        { return 3; }
// int t0()            { return 2; }
// int t1()            { return 6; }
// int t2()            { return 7; }
// int t3()            { return 8; }
// int t4()            { return 9; }
// int t5()            { return 10; }
// int t6()            { return 11; }
// int t7()            { return 12; }

// Uninterpreted functions
