package t1;

Object t1_t1(Object self) {
    return self;
}

harness void m() {
  Object self = Object_Object(new Object(__cid=Object()));
  Object s = Stack_Stack(new Object(__cid=Stack()));
  Object o1 = Object_Object(new Object(__cid=Object()));
  Object o2 = Object_Object(new Object(__cid=Object()));
  (s.__cid == Stack() ? push_E@Stack(s, o1) : null);
  (s.__cid == Stack() ? push_E@Stack(s, o2) : null);
  Object poppsh12 = (s.__cid == Stack() ? pop@Stack(s) : null);
  assert (poppsh12.__cid == String() ? equals_Object@String(poppsh12, o2) : poppsh12.__cid == t1() ? equals_Object@Object(poppsh12, o2) : poppsh12.__cid == Stack() ? equals_Object@Object(poppsh12, o2) : poppsh12.__cid == Object() ? equals_Object@Object(poppsh12, o2) : 0);
}

