package t4;

Object t4_t4(Object self) {
    return self;
}

harness void m() {
  Object self = Object_Object(new Object(__cid=Object()));
  Object s = Stack_Stack(new Object(__cid=Stack()));
  Object o1 = Object_Object(new Object(__cid=Object()));
  Object o2 = Object_Object(new Object(__cid=Object()));
  (s.__cid == Stack() ? push_E@Stack(s, o1) : null);
  (s.__cid == Stack() ? push_E@Stack(s, o2) : null);
  (s.__cid == Stack() ? pop@Stack(s) : null);
  Object poppoppsh12 = (s.__cid == Stack() ? pop@Stack(s) : null);
  assert (poppoppsh12.__cid == String() ? equals_Object@String(poppoppsh12, o1) : poppoppsh12.__cid == Stack() ? equals_Object@Object(poppoppsh12, o1) : poppoppsh12.__cid == t4() ? equals_Object@Object(poppoppsh12, o1) : poppoppsh12.__cid == Object() ? equals_Object@Object(poppoppsh12, o1) : 0);
}

