package t5;

Object t5_t5(Object self) {
    return self;
}

harness void m() {
  Object self = Object_Object(new Object(__cid=Object()));
  Object s = Stack_Stack(new Object(__cid=Stack()));
  Object o1 = Object_Object(new Object(__cid=Object()));
  Object o2 = Object_Object(new Object(__cid=Object()));
  Object o3 = Object_Object(new Object(__cid=Object()));
  Object o4 = Object_Object(new Object(__cid=Object()));
  Object o5 = Object_Object(new Object(__cid=Object()));
  (s.__cid == Stack() ? push_E@Stack(s, o1) : null);
  (s.__cid == Stack() ? pop@Stack(s) : null);
  (s.__cid == Stack() ? push_E@Stack(s, o2) : null);
  (s.__cid == Stack() ? pop@Stack(s) : null);
  (s.__cid == Stack() ? push_E@Stack(s, o3) : null);
  (s.__cid == Stack() ? pop@Stack(s) : null);
  (s.__cid == Stack() ? push_E@Stack(s, o4) : null);
  (s.__cid == Stack() ? pop@Stack(s) : null);
  (s.__cid == Stack() ? push_E@Stack(s, o5) : null);
  Object poppsh5 = (s.__cid == Stack() ? pop@Stack(s) : null);
  assert (poppsh5.__cid == String() ? equals_Object@String(poppsh5, o5) : poppsh5.__cid == t5() ? equals_Object@Object(poppsh5, o5) : poppsh5.__cid == Stack() ? equals_Object@Object(poppsh5, o5) : poppsh5.__cid == Object() ? equals_Object@Object(poppsh5, o5) : 0);
}

