package meta;

// distinct class IDs
int ArrayList()      { return 8; }
int Assert()         { return 7; }
int Boolean()        { return 12; }
int Bucketing()      { return 2; }
int BucketingTest()  { return 3; }
int CharSequence()   { return 10; }
int Character()      { return 9; }
int HashTable()      { return 5; }
int Integer()        { return 11; }
int Object()         { return 1; }
int Pair()           { return 4; }
int String()         { return 6; }
int Array()          { return -1; }
int _int()           { return -2; }
int _char()          { return -3; }
int _bit()           { return -4; }
int _float()         { return -5; }
int _double()        { return -6; }

// Uninterpreted functions
