package t1;

// len(concat(s1,s2)) + len(concat(s3,s4)) == len(s1) + len(s2) + len(s3) + len(s4)
harness void mn() {
  Object s1 = String_String_char_int_int(new Object(__cid=String()),
					 new Array_char(length=7+1, A="hello, "), 0, 7);
  Object s2 = String_String_char_int_int(new Object(__cid=String()),
					 new Array_char(length=6+1, A="world!"), 0, 6);
  Object s3 = String_String_char_int_int(new Object(__cid=String()),
					 new Array_char(length=13+1, A="ALLWORKNOPLAY"), 0, 13);
  Object s4 = String_String_char_int_int(new Object(__cid=String()),
					 new Array_char(length=19+1, A="MAKESJACKADULLBOY!!"), 0, 19);
  int len1234 = (s1.__cid == String() ? length@String(s1) : 0) +
                (s2.__cid == String() ? length@String(s2) : 0) +
                (s3.__cid == String() ? length@String(s3) : 0) +
                (s4.__cid == String() ? length@String(s4) : 0);

  Object c12 = (s1.__cid == String() ? concat_String@String(s1, s2) : null);
  Object c34 = (s3.__cid == String() ? concat_String@String(s3, s4) : null);
  int lc12c34 = (c12.__cid == String() ? length@String(c12) : 0) +
                (c34.__cid == String() ? length@String(c34) : 0);
  assert lc12c34 == len1234;
}
