package SecretKeySpec;

adt SecretKeySpec {
    Secretkeyspec  { }
    Getencoded     { SecretKeySpec self; }
}

Object SecretKeySpec_SecretKeySpec() {
    return new Object(__cid=SecretKeySpec(), _secretkeyspec=new Secretkeyspec());
}

Object getEncoded_Object(Object self) {
    return new Object(__cid=SecretKeySpec(), _secretkeyspec=new Getencoded(self=self._secretkeyspec));
}

Object xform_SecretKeySpec(SecretKeySpec self) {
  switch(self) {
  case Secretkeyspec: {
    return xform_secretkeyspec_SecretKeySpec(self);
  }
  case Getencoded: {
    return xform_getEncoded_SecretKeySpec(self.self);
  }
  }

  return null;
}
Object xform_getEncoded_SecretKeySpec(SecretKeySpec self) {
  switch(self) {
  case Secretkeyspec: { assert false; }
  case Getencoded: { assert false; }
  }

  return null;
}
Object xform_secretkeyspec_SecretKeySpec(SecretKeySpec self) {
  switch(self) {
  case Secretkeyspec: { assert false; }
  case Getencoded: { assert false; }
  }

  return null;
}
