package ArrayList;

adt ArrayList {
    Arraylist       { }
    Add_e             { ArrayList self; Object e; }
    Addb_e            { ArrayList self; Object e; }
    Getb_int            { ArrayList self; Object i; }
    Setb_int_e            { ArrayList self; Object i; Object e; }
    Get_int             { ArrayList self; Object i; }
    Set_int_e             { ArrayList self; Object i; Object e; }
    Ensurecapacity_int  { ArrayList self; Object n; }
    Size            { ArrayList self; }
}

Object ArrayList_ArrayList() {
    return new Object(__cid=ArrayList(), _arraylist=new Arraylist());
}

Object add_Object_E(Object self, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Add_e(self=self._arraylist, e=e));
}

Object addb_Object_E(Object self, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Addb_e(self=self._arraylist, e=e));
}

Object getb_Object_int(Object self, Object i) {
    return new Object(__cid=ArrayList(), _arraylist=new Getb_int(self=self._arraylist, i=i));
}

Object setb_Object_int_E(Object self, Object i, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Setb_int_e(self=self._arraylist, i=i, e=e));
}

Object get_Object_int(Object self, Object i) {
    return new Object(__cid=ArrayList(), _arraylist=new Get_int(self=self._arraylist, i=i));
}

Object set_Object_int_E(Object self, Object i, Object e) {
    return new Object(__cid=ArrayList(), _arraylist=new Set_int_e(self=self._arraylist, i=i, e=e));
}

Object ensureCapacity_Object_int(Object self, Object n) {
    return new Object(__cid=ArrayList(), _arraylist=new Ensurecapacity_int(self=self._arraylist, n=n));
}

Object size_Object(Object self) {
    return new Object(__cid=ArrayList(), _arraylist=new Size(self=self._arraylist));
}

Object xform_ArrayList(ArrayList self) {
  switch(self) {
  case Arraylist: {
    return xform_arraylist_ArrayList(self);
  }
  case Add_e: {
    return xform_add_ArrayList_E(self.self, self.e);
  }
  case Addb_e: {
    return xform_addb_ArrayList_E(self.self, self.e);
  }
  case Getb_int: {
    return xform_getb_ArrayList_int(self.self, self.i);
  }
  case Setb_int_e: {
    return xform_setb_ArrayList_int_E(self.self, self.i, self.e);
  }
  case Get_int: {
    return xform_get_ArrayList_int(self.self, self.i);
  }
  case Set_int_e: {
    return xform_set_ArrayList_int_E(self.self, self.i, self.e);
  }
  case Ensurecapacity_int: {
    return xform_ensureCapacity_ArrayList_int(self.self, self.n);
  }
  case Size: {
    return xform_size_ArrayList(self.self);
  }
  }

  return null;
}
Object xform_addb_ArrayList_E(ArrayList self, Object e) {
  switch(self) {
  case Arraylist: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_size_ArrayList(ArrayList self) {
  switch(self) {
  case Arraylist: {
    return (new Object(__cid=-2, _int=0));
  }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: {
    return (new Object(__cid=-2, _int=xform_size_ArrayList(self.self)._int + (new Object(__cid=-2, _int=1))._int));
  }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: {
    return xform_size_ArrayList(self.self);
  }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_get_ArrayList_int(ArrayList self, Object i) {
  switch(self) {
  case Arraylist: {
    return null;
  }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: {
    return (xform_size_ArrayList(self.self)._int == i._int - (new Object(__cid=-2, _int=1))._int ? self.e : xform_get_ArrayList_int(self.self, i));
    /* assert false; */
    /* return (xform_size_ArrayList(self.self)._int == i._int ? self.e : xform_get_ArrayList_int(self.self, i)); */
  }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: {
    return (i._int == self.i._int ? self.e : xform_get_ArrayList_int(self.self, i));
  }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_getb_ArrayList_int(ArrayList self, Object i) {
  switch(self) {
  case Arraylist: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_add_ArrayList_E(ArrayList self, Object e) {
  switch(self) {
  case Arraylist: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_setb_ArrayList_int_E(ArrayList self, Object i, Object e) {
  switch(self) {
  case Arraylist: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_ensureCapacity_ArrayList_int(ArrayList self, Object n) {
  switch(self) {
  case Arraylist: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_set_ArrayList_int_E(ArrayList self, Object i, Object e) {
  switch(self) {
  case Arraylist: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
Object xform_arraylist_ArrayList(ArrayList self) {
  switch(self) {
  case Arraylist: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Add_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Addb_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Getb_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Setb_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Get_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Set_int_e: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Ensurecapacity_int: { new Object(__cid=ArrayList(), _arraylist=self); }
  case Size: { new Object(__cid=ArrayList(), _arraylist=self); }
  }

  return null;
}
