package Mac;

adt Mac {
    Mac_empty  { }
    Init_secretkeyspec       { Mac self; Object key; }
    Initb_secretkeyspec      { Mac self; Object key; }
    Dofinal_object    { Mac self; Object text; }
}

Object Mac_Mac() {
    return new Object(__cid=Mac(), _mac=new Mac_empty());
}

Object init_Object_SecretKeySpec(Object self, Object key) {
    return new Object(__cid=Mac(), _mac=new Init_secretkeyspec(self=self._mac, key=key));
}

Object initb_Object_SecretKeySpec(Object self, Object key) {
    return new Object(__cid=Mac(), _mac=new Initb_secretkeyspec(self=self._mac, key=key));
}

Object doFinal_Object_Object(Object self, Object text) {
    return new Object(__cid=Mac(), _mac=new Dofinal_object(self=self._mac, text=text));
}

Object xform_Mac(Mac self) {
  switch(self) {
  case Mac_empty: {
    return xform_mac_Mac(self);
  }
  case Init_secretkeyspec: { new Object(__cid=Mac(), _mac=self); }
  case Initb_secretkeyspec: { new Object(__cid=Mac(), _mac=self); }
  case Dofinal_object: { new Object(__cid=Mac(), _mac=self); }
  }

  return null;
}
Object xform_doFinal_Mac_Object(Mac self, Object text) {
  switch(self) {
  case Mac_empty: { return new Object(__cid=Mac(), _mac=self); }
  case Init_secretkeyspec: { return new Object(__cid=Mac(), _mac=self); }
  case Initb_secretkeyspec: {
    return text;
  }
  case Dofinal_object: { return new Object(__cid=Mac(), _mac=self); }
  }

  return null;
}
Object xform_init_Mac_SecretKeySpec(Mac self, Object key) {
  switch(self) {
  case Mac_empty: { return new Object(__cid=Mac(), _mac=self); }
  case Init_secretkeyspec: { return new Object(__cid=Mac(), _mac=self); }
  case Initb_secretkeyspec: { return new Object(__cid=Mac(), _mac=self); }
  case Dofinal_object: { return new Object(__cid=Mac(), _mac=self); }
  }

  return null;
}
Object xform_initb_Mac_SecretKeySpec(Mac self, Object key) {
  switch(self) {
  case Mac_empty: { return new Object(__cid=Mac(), _mac=self); }
  case Init_secretkeyspec: { return new Object(__cid=Mac(), _mac=self); }
  case Initb_secretkeyspec: { return new Object(__cid=Mac(), _mac=self); }
  case Dofinal_object: { return new Object(__cid=Mac(), _mac=self); }
  }

  return null;
}
Object xform_mac_Mac(Mac self) {
  switch(self) {
  case Mac_empty: { return new Object(__cid=Mac(), _mac=self); }
  case Init_secretkeyspec: { return new Object(__cid=Mac(), _mac=self); }
  case Initb_secretkeyspec: { return new Object(__cid=Mac(), _mac=self); }
  case Dofinal_object: { return new Object(__cid=Mac(), _mac=self); }
  }

  return null;
}
