package Axiom_String;

harness void mn() {
  Object self = Object_Object(new Object(__cid=Object()));
  test_7_6(self);
  // test_100_200(self); 
}

void test_7_6(Object self) {
  Object s1 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=7+1, A="hello, "), 0, 7);
  Object s2 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=6+1, A="world!"), 0, 6);
  Object s3 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=7+1, A="BEN"), 0, 3);
  Object s4 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=6+1, A="JOSH"), 0, 4);
  Object s5 = (s1.__cid == String() ? concat_String@String(s1, s2) : null);
  Object s6 = (s3.__cid == String() ? concat_String@String(s3, s4) : null);
  Object s7 = (s5.__cid == String() ? concat_String@String(s5, s6) : null);

  int len12 = (s1.__cid == String() ? length@String(s1) : 0) + (s2.__cid == String() ? length@String(s2) : 0);
  int len5 = (s5.__cid == String() ? length@String(s5) : 0);
  assert len5 == len12;

  int len34 = (s3.__cid == String() ? length@String(s3) : 0) + (s4.__cid == String() ? length@String(s4) : 0);
  int len6 = (s6.__cid == String() ? length@String(s6) : 0);
  assert len6 == len34;

  int len1234 = len12 + len34;
  int len7 = (s7.__cid == String() ? length@String(s7) : 0);
  assert len7 == len1234;

  int i;

  Object s8 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=6+1, A="SEED1"), 0, 5);
  Object s9 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=6+1, A="SEED2"), 0, 5);
  Object s10 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=6+1, A=""), 0, 0);

  int looplen = 0;

  for (i = 0; i < 10; i++) {
     Object s11 = (s8.__cid == String() ? concat_String@String(s8, s8) : null);  

     Object s12 = (s9.__cid == String() ? concat_String@String(s9, s9) : null);  

     Object s13=(s11.__cid == String() ? concat_String@String(s11, s12) : null); 

     s10 = (s10.__cid == String() ? concat_String@String(s10, s13) : null);     
     looplen = looplen + (s8.__cid == String() ? length@String(s8) : 0) + (s9.__cid == String() ? length@String(s9) : 0) + (s8.__cid == String() ? length@String(s8) : 0) + (s9.__cid == String() ? length@String(s9) : 0);
  } 

  int len10 = (s10.__cid == String() ? length@String(s10) : 0);
  assert looplen == len10;
}

// void test_100_200(Object self) {
//   Object s1 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=100+1, A="0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"), 0, 100);
//   Object s2 = String_String_char_int_int(new Object(__cid=String()), new Array_char(length=200+1, A="01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"), 0, 200);
//   Object s3 = (s1.__cid == String() ? concat_String@String(s1, s2) : null);
//   int len12 = (s1.__cid == String() ? length@String(s1) : 0) + (s2.__cid == String() ? length@String(s2) : 0);
//   int len3 = (s3.__cid == String() ? length@String(s3) : 0);
//   assert len3 == len12;
// }

