package ArrayListTester;

Object ArrayListTester_ArrayListTester(Object self) {
    return self;
}

harness void mn_int(int l) {
  Object self = Object_Object(new Object(__cid=Object()));
  assume l >= 0;
  Object a = ArrayList_ArrayList();
  for (int i = 0; i < l; i++) {
    Object j = Integer_Integer_int(new Object(__cid=Integer()), i);
    (a.__cid == ArrayList() ? add_Object_Object@ArrayList(a, j) : null); a = (a.__cid == ArrayList() ? addb_Object_Object@ArrayList(a, j) : null);
  }
  int sz = (a.__cid == ArrayList() ? size_Object@ArrayList(a) : 0);
  assert sz == l;
}

