package test;

harness void mn() {
  if (TID==0) t0();
  else if (TID==1) t1();
  else if (TID==2) t2();
  else if (TID==3) t3();
  else if (TID==4) t4();
  else if (TID==5) t5();
  else if (TID==6) t6();
  else if (TID==7) t7();
}

/*****************************************************************************/
/* len(concat()) tests */
/*****************************************************************************/
// len(concat(s1,s2)) == len(s1) + len(s2)
void t0() {
  Object s1 = string();
  Object s2 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len12 = plus(len1.t, len2.t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.t) : null);
  assert xform(lenc12.t, ??) === len12.t;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) == len(s1) + len(s2) + len(s3) + len(s4)
void t1() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);
  Object len1234 = plus(plus(len1.t,len2.t).t,plus(len3.t, len4.t).t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.t) : null);
  Object lenc34 = (c34.__cid == String() ? length(c34.t) : null);
  Object lenc12c34 = plus(lenc12.t, lenc34.t);
  assert xform(lenc12c34.t, ??) === len1234.t;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6)
void t2() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);
  Object len5 = (s5.__cid == String() ? length(s5.t) : null);
  Object len6 = (s6.__cid == String() ? length(s6.t) : null);
  Object len123456 = plus(plus(plus(len1.t,len2.t).t,plus(len3.t,len4.t).t).t,plus(len5.t,len6.t).t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.t, s6.t) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.t) : null);
  Object lenc34 = (c34.__cid == String() ? length(c34.t) : null);
  Object lenc56 = (c56.__cid == String() ? length(c56.t) : null);
  Object lenc12c34c56 = plus(plus(lenc12.t,lenc34.t).t,lenc56.t);
  assert xform(lenc12c34c56.t, ??) === len123456.t;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) + len(concat(s7,s8)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6) + len(s7) + len(s8)
void t3() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();
  Object s7 = string();
  Object s8 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);
  Object len5 = (s5.__cid == String() ? length(s5.t) : null);
  Object len6 = (s6.__cid == String() ? length(s6.t) : null);
  Object len7 = (s7.__cid == String() ? length(s7.t) : null);
  Object len8 = (s8.__cid == String() ? length(s8.t) : null);
  Object len12345678 = plus(plus(plus(len1.t,len2.t).t,plus(len3.t,len4.t).t).t,
			    plus(plus(len5.t,len6.t).t,plus(len7.t,len8.t).t).t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.t, s6.t) : null);
  Object c78 = (s7.__cid == String() ? concat(s7.t, s8.t) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.t) : null);
  Object lenc34 = (c34.__cid == String() ? length(c34.t) : null);
  Object lenc56 = (c56.__cid == String() ? length(c56.t) : null);
  Object lenc78 = (c78.__cid == String() ? length(c78.t) : null);
  Object lenc12c34c56c78 = plus(plus(lenc12.t,lenc34.t).t,plus(lenc56.t,lenc78.t).t);
  assert xform(lenc12c34c56c78.t, ??) === len12345678.t;
}

// len(concat(concat(s1,s2),s3) == len(s1) + len(s2) + len(s3)
void t4() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len123 = plus(plus(len1.t,len2.t).t,len3.t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.t, s3.t) : null);
  Object lencc123 = (cc123.__cid == String() ? length(cc123.t) : null);
  assert xform(lencc123.t, ??) === len123.t;
}

// len(concat(concat(concat(s1,s2),s3),s4)) == len(s1) + len(s2) + len(s3) + len(s4)
void t5() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);
  Object len1234 = plus(plus(plus(len1.t,len2.t).t,len3.t).t,len4.t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.t, s3.t) : null);
  Object ccc1234 = (cc123.__cid == String() ? concat(cc123.t, s4.t) : null);
  Object lenccc1234 = (ccc1234.__cid == String() ? length(ccc1234.t) : null);
  assert xform(lenccc1234.t, ??) === len1234.t;
}

// len(concat(concat(concat(s1,s2),s3),concat(s4,s5)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5)
void t6() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);
  Object len5 = (s5.__cid == String() ? length(s5.t) : null);
  Object len12345 = plus(plus(plus(len1.t,len2.t).t,len3.t).t,
			 plus(len4.t,len5.t).t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c45 = (s4.__cid == String() ? concat(s4.t, s5.t) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.t, s3.t) : null);
  Object ccc123c45 = (cc123.__cid == String() ? concat(cc123.t,c45.t) : null);
  Object lenccc123c45 = (ccc123c45.__cid == String() ? length(ccc123c45.t) : null);
  assert xform(lenccc123c45.t, ??) === len12345.t;
}

// len(concat(s1,concat(s1,concat(s1,concat(s1,s2))))) == len(s1) + len(s1) + len(s1) + len(s1) + len(s2)
void t7() {
  Object s1 = string();
  Object s2 = string();
  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len11112 = plus(len1.t,plus(len1.t,plus(len1.t,plus(len1.t,len2.t).t).t).t);
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c1c12 = (s1.__cid == String() ? concat(s1.t, c12.t) : null); 
  Object c1c1c12 = (s1.__cid == String() ? concat(s1.t, c1c12.t) : null); 
  Object c1c1c1c12 = (s1.__cid == String() ? concat(s1.t, c1c1c12.t) : null); 
  Object lenc1c1c1c12 = (c1c1c1c12.__cid == String() ? length(c1c1c1c12.t) : null);
  assert xform(lenc1c1c1c12.t, ??) === len11112.t;
}
