package test;

harness void mn() {
  if (TID == 0) t0();
  else if (TID == 1) t1();
  else if (TID == 2) t2();
  else if (TID == 3) t3();
  else if (TID == 4) t4();
  else if (TID == 5) t5();
  else if (TID == 6) t6();
  else if (TID == 7) t7();
  else if (TID == 8) t8();
  else if (TID == 9) t9();
  else if (TID == 10) t10();
  else if (TID == 11) t11();
  else if (TID == 12) t12();
  else if (TID == 13) t13();
  else if (TID == 14) t14();
}

void t0() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  Object gxpx = (h.__cid == HashMap_NoHash() ? get_K@HashMap_NoHash(h, x) : null);
  assert (gxpx.__cid == HashMap_NoHash_Node() ? equals_Object@Object(gxpx, y) : gxpx.__cid == Object() ? equals_Object@Object(gxpx, y) : 0);
}

void t1() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object w = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, w, z) : null);
  Object gxpxw = (h.__cid == HashMap_NoHash() ? get_K@HashMap_NoHash(h, x) : null);
  assert (gxpxw.__cid == HashMap_NoHash_Node() ? equals_Object@Object(gxpxw, y) : gxpxw.__cid == Object() ? equals_Object@Object(gxpxw, y) : 0);
}

void t2() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, z) : null);
  Object gxpxx = (h.__cid == HashMap_NoHash() ? get_K@HashMap_NoHash(h, x) : null);
  assert (gxpxx.__cid == HashMap_NoHash_Node() ? equals_Object@Object(gxpxx, z) : gxpxx.__cid == Object() ? equals_Object@Object(gxpxx, z) : 0);
}

void t3() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object w = Object_Object(new Object(__cid=Object()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  Object a = Object_Object(new Object(__cid=Object()));
  Object b = Object_Object(new Object(__cid=Object()));
  Object c = Object_Object(new Object(__cid=Object()));
  Object d = Object_Object(new Object(__cid=Object()));
  Object e = Object_Object(new Object(__cid=Object()));
  Object f = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, w, z) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, a, b) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, c, d) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, e, f) : null);
  Object gxpxwace = (h.__cid == HashMap_NoHash() ? get_K@HashMap_NoHash(h, x) : null);
  assert (gxpxwace.__cid == HashMap_NoHash_Node() ? equals_Object@Object(gxpxwace, y) : gxpxwace.__cid == Object() ? equals_Object@Object(gxpxwace, y) : 0);
}

void t4() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, z) : null);
  (h.__cid == HashMap_NoHash() ? remove_K@HashMap_NoHash(h, x) : null);
  Object gxrxpxx = (h.__cid == HashMap_NoHash() ? get_K@HashMap_NoHash(h, x) : null);
  assert gxrxpxx == null;
}

void t5() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? remove_K@HashMap_NoHash(h, x) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, z) : null);
  Object gxpxrxpx = (h.__cid == HashMap_NoHash() ? get_K@HashMap_NoHash(h, x) : null);
  assert (gxpxrxpx.__cid == HashMap_NoHash_Node() ? equals_Object@Object(gxpxrxpx, z) : gxpxrxpx.__cid == Object() ? equals_Object@Object(gxpxrxpx, z) : 0);
}

void t6() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  assert (h.__cid == HashMap_NoHash() ? containsKey_K@HashMap_NoHash(h, x) : 0);
}

void t7() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object w = Object_Object(new Object(__cid=Object()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  Object a = Object_Object(new Object(__cid=Object()));
  Object b = Object_Object(new Object(__cid=Object()));
  Object c = Object_Object(new Object(__cid=Object()));
  Object d = Object_Object(new Object(__cid=Object()));
  Object e = Object_Object(new Object(__cid=Object()));
  Object f = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, w, z) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, a, b) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, c, d) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, e, f) : null);
  assert (h.__cid == HashMap_NoHash() ? containsKey_K@HashMap_NoHash(h, x) : 0);
}

void t8() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  assert !(h.__cid == HashMap_NoHash() ? containsKey_K@HashMap_NoHash(h, z) : 0);
}

void t9() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, z) : null);
  (h.__cid == HashMap_NoHash() ? remove_K@HashMap_NoHash(h, x) : null);
  assert !(h.__cid == HashMap_NoHash() ? containsKey_K@HashMap_NoHash(h, x) : 0);
}

void t10() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? remove_K@HashMap_NoHash(h, x) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, z) : null);
  assert (h.__cid == HashMap_NoHash() ? containsKey_K@HashMap_NoHash(h, x) : 0);
}

void t11() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  assert (h.__cid == HashMap_NoHash() ? containsValue_V@HashMap_NoHash(h, y) : 0);
}

void t12() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object w = Object_Object(new Object(__cid=Object()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  Object a = Object_Object(new Object(__cid=Object()));
  Object b = Object_Object(new Object(__cid=Object()));
  Object c = Object_Object(new Object(__cid=Object()));
  Object d = Object_Object(new Object(__cid=Object()));
  Object e = Object_Object(new Object(__cid=Object()));
  Object f = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, w, z) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, a, b) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, c, d) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, e, f) : null);
  assert (h.__cid == HashMap_NoHash() ? containsValue_V@HashMap_NoHash(h, y) : 0);
}

void t13() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, z) : null);
  assert !(h.__cid == HashMap_NoHash() ? containsValue_V@HashMap_NoHash(h, y) : 0);
}

void t14() {
  Object h = HashMap_NoHash_HashMap_NoHash(new Object(__cid=HashMap_NoHash()));
  Object w = Object_Object(new Object(__cid=Object()));
  Object x = Object_Object(new Object(__cid=Object()));
  Object y = Object_Object(new Object(__cid=Object()));
  Object z = Object_Object(new Object(__cid=Object()));
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, x, y) : null);
  (h.__cid == HashMap_NoHash() ? put_K_V@HashMap_NoHash(h, w, z) : null);
  (h.__cid == HashMap_NoHash() ? remove_K@HashMap_NoHash(h, x) : null);
  assert !(h.__cid == HashMap_NoHash() ? containsValue_V@HashMap_NoHash(h, y) : 0);
}

