package t0;

// len(concat(s1,s2)) == len(s1) + len(s2)
harness void mn() {
  Object s1 = string();
  Object s2 = string();

  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);

  Object len12 = plus(len1.t, len2.t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.t) : null);

  assert xform(lenc12.t,??) === len12.t;
}
