package t1;

// len(concat(s1,s2)) + len(concat(s3,s4)) == len(s1) + len(s2) + len(s3) + len(s4)
harness void mn() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object pl1234 = plus(plus((s1.__cid == String() ? length(s1.t).t : null),
			    (s2.__cid == String() ? length(s2.t).t : null)).t,
		       plus((s3.__cid == String() ? length(s3.t).t : null),
			    (s4.__cid == String() ? length(s4.t).t : null)).t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object plc12c34 = plus((c12.__cid == String() ? length(c12.t).t : null),
			 (c34.__cid == String() ? length(c34.t).t : null));
  assert xform(plc12c34.t) == pl1234.t;
}
