package t2;

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6)
harness void mn() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();

  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);
  Object len5 = (s5.__cid == String() ? length(s5.t) : null);
  Object len6 = (s6.__cid == String() ? length(s6.t) : null);

  Object len123456 = plus(
			  plus(
			       plus(len1.t,len2.t).t,
			       plus(len3.t,len4.t).t).t,
			  plus(len5.t,len6.t).t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.t, s6.t) : null);

  Object lenc12 = (c12.__cid == String() ? length(c12.t) : null);
  Object lenc34 = (c34.__cid == String() ? length(c34.t) : null);
  Object lenc56 = (c56.__cid == String() ? length(c56.t) : null);

  Object lenc12c34c56 = plus(
			     plus(
				  lenc12.t,
				  lenc34.t).t,
			     lenc56.t);

  assert len123456.t === len123456.t;
  /* assert xform(lenc12c34c56.t, ??) === len123456.t; */
}
