package t3;

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) + len(concat(s7,s8)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6) + len(s7) + len(s8)
harness void mn() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();
  Object s7 = string();
  Object s8 = string();

  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len3 = length(s3.t);
  Object len4 = length(s4.t);
  Object len5 = length(s5.t);
  Object len6 = length(s6.t);
  Object len7 = length(s7.t);
  Object len8 = length(s8.t);

  Object len12345678 = plus(
			    plus(
				 plus(len1.t,len2.t).t,
				 plus(len3.t,len4.t).t).t,
			    plus(
				 plus(len5.t,len6.t).t,
				 plus(len7.t,len8.t).t).t);
  
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.t, s6.t) : null);
  Object c78 = (s7.__cid == String() ? concat(s7.t, s8.t) : null);

  Object lenc12 = length(c12.t);
  Object lenc34 = length(c34.t);
  Object lenc56 = length(c56.t);
  Object lenc78 = length(c78.t);

  Object lenc12c34c56c78 = plus(plus(lenc12.t,lenc34.t).t,plus(lenc56.t,lenc78.t).t);

  assert xform(lenc12c34c56c78.t, ??) == len12345678.t;
}
