package t4;

// len(concat(concat(s1,s2),s3) == len(s1) + len(s2) + len(s3)
harness void mn() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();

  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);

  Object len123 = plus(plus(len1.t,len2.t).t,len3.t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.t, s3.t) : null);

  Object lencc123 = (cc123.__cid == String() ? length(cc123.t) : null);
    
  assert xform(lencc123.t, ??) === len123.t;
}
