package t5;

// len(concat(concat(concat(s1,s2),s3),s4)) == len(s1) + len(s2) + len(s3) + len(s4)
harness void mn() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();

  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);

  Object len1234 = plus(plus(len1.t,len2.t).t,plus(len3.t,len4.t).t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s1.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c12c34 = (c12.__cid == String() ? concat(c12.t, c34.t) : null);

  Object lenc12c34 = (c12c34.__cid == String() ? length(c12c34.t) : null);
    
  assert xform(lenc12c34.t, ??) === len1234.t;
}
