package t6;

// len(concat(concat(concat(s1,s2),s3),concat(s4,s5)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5)
harness void mn() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();

  Object len1 = (s1.__cid == String() ? length(s1.t) : null);
  Object len2 = (s2.__cid == String() ? length(s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);
  Object len4 = (s4.__cid == String() ? length(s4.t) : null);
  Object len5 = (s5.__cid == String() ? length(s5.t) : null);

  Object len12345 = plus(plus(plus(len1.t,len2.t).t,
			      plus(len3.t,len4.t).t).t,
			 len5.t);

  /* Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null); */
  /* Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null); */
  /* Object c1234 = (c12.__cid == String() ? concat(c12.t, c34.t) : null); */
  /* Object c12c345 = (c1234.__cid == String() ? concat(c1234.t, s5.t) : null); */

  /* Object lenc12c345 = (c12c345.__cid == String() ? length(c12c345.t) : null); */
    
  assert len12345.t === len12345.t;
  /* assert xform(lenc12c345.t, ??) === len12345.t; */
}
