package test;

int TID=2;

harness void mn() {
  if (TID==0) t0();
  else if (TID==1) t1();
  else if (TID==2) t2();
  else if (TID==3) t3();
  else if (TID==4) t4();
  else if (TID==5) t5();
  else if (TID==6) t6();
}

// len(concat(s1,s2)) == len(s1) + len(s2)
void t0() {
  Object s1 = string();
  Object s2 = string();
  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len12 = plus(len1.t, len2.t);

  Object s3 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object len3 = (s3.__cid == String() ? length(s3.t) : null);

  assert xform(len3.t, ??) == len12.t;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) == len(s1) + len(s2) + len(s3) + len(s4)
void t1() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len3 = length(s3.t);
  Object len4 = length(s4.t);
  Object len1234 = plus(plus(len1.t,len2.t).t,
			plus(len3.t, len4.t).t);
  
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object lenc12c34 = plus((c12.__cid == String() ? length(c12.t).t : null),
			  (c34.__cid == String() ? length(c34.t).t : null));
  assert xform(lenc12c34.t, ??) != len1234.t;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6)
void t2() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();

  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len3 = length(s3.t);
  Object len4 = length(s4.t);
  Object len5 = length(s5.t);
  Object len6 = length(s6.t);

  Object len123456 = plus(
			  plus(
			       plus(len1.t,len2.t).t,
			       plus(len3.t,len4.t).t).t,
			  plus(len5.t,len6.t).t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.t, s6.t) : null);

  Object lenc12 = length(c12.t);
  Object lenc34 = length(c34.t);
  Object lenc56 = length(c56.t);

  Object lenc12c34c56 = plus(plus(lenc12.t,lenc34.t).t,lenc56.t);

  assert xform(lenc12c34c56.t, ??) == len123456.t;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) + len(concat(s7,s8)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6) + len(s7) + len(s8)
void t3() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();
  Object s7 = string();
  Object s8 = string();

  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len3 = length(s3.t);
  Object len4 = length(s4.t);
  Object len5 = length(s5.t);
  Object len6 = length(s6.t);
  Object len7 = length(s7.t);
  Object len8 = length(s8.t);

  Object len12345678 = plus(
			    plus(
				 plus(len1.t,len2.t).t,
				 plus(len3.t,len4.t).t).t,
			    plus(
				 plus(len5.t,len6.t).t,
				 plus(len7.t,len8.t).t).t);
  
  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.t, s6.t) : null);
  Object c78 = (s7.__cid == String() ? concat(s7.t, s8.t) : null);

  Object lenc12 = length(c12.t);
  Object lenc34 = length(c34.t);
  Object lenc56 = length(c56.t);
  Object lenc78 = length(c78.t);

  Object lenc12c34c56c78 = plus(plus(lenc12.t,lenc34.t).t,plus(lenc56.t,lenc78.t).t);

  assert xform(lenc12c34c56c78.t, ??) == len12345678.t;
}

// len(concat(concat(s1,s2),s3) == len(s1) + len(s2) + len(s3)
void t4() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();

  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len3 = length(s3.t);

  Object len123 = plus(plus(len1.t,len2.t).t,len3.t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.t, s3.t) : null);
  Object lencc123 = length(cc123.t);
    
  assert xform(lencc123.t, ??) == len123.t;
}

// len(concat(concat(concat(s1,s2),s3),s4)) == len(s1) + len(s2) + len(s3) + len(s4)
void t5() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();

  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len3 = length(s3.t);
  Object len4 = length(s4.t);

  Object len1234 = plus(plus(len1.t,len2.t).t,plus(len3.t,len4.t).t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s1.__cid == String() ? concat(s3.t, s4.t) : null);
  Object cc1234 = (c12.__cid == String() ? concat(c12.t, c34.t) : null);
  Object lencc1234 = length(cc1234.t);
    
  assert xform(lencc1234.t, ??) == len1234.t;
}

// len(concat(concat(concat(s1,s2),s3),concat(s4,s5)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5)
void t6() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();

  Object len1 = length(s1.t);
  Object len2 = length(s2.t);
  Object len3 = length(s3.t);
  Object len4 = length(s4.t);
  Object len5 = length(s5.t);

  Object len12345 = plus(plus(plus(len1.t,len2.t).t,
			      plus(len3.t,len4.t).t).t,
			 len5.t);

  Object c12 = (s1.__cid == String() ? concat(s1.t, s2.t) : null);
  Object c34 = (s1.__cid == String() ? concat(s3.t, s4.t) : null);
  Object c1234 = (c12.__cid == String() ? concat(c12.t, c34.t) : null);
  Object cc12345 = (c1234.__cid == String() ? concat(c1234.t, s5.t) : null);
  Object lencc12345 = length(cc12345.t);
    
  assert xform(lencc12345.t, ??) == len12345.t;
}
