package test_p;

harness void mn() {
  if (TID==0) t0();
  else if (TID==1) t1();
  else if (TID==2) t2();
  else if (TID==3) t3();
  else if (TID==4) t4();
  else if (TID==5) t5();
  else if (TID==6) t6();
  else if (TID==7) t7();
  else if (TID==8) t8();
}

/*****************************************************************************/
/* len(concat()) tests */
/*****************************************************************************/
// len(concat(s1,s2)) == len(s1) + len(s2)
void t0() {
  Object s1 = string();
  Object s2 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  int len12 = len(len1.iterm) + len(len2.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.sterm) : null);
  assert arithmetize(xform(lenc12.iterm)) == len12;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) == len(s1) + len(s2) + len(s3) + len(s4)
void t1() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  Object len3 = (s3.__cid == String() ? length(s3.sterm) : null);
  Object len4 = (s4.__cid == String() ? length(s4.sterm) : null);
  int len1234 = len(len1.iterm) + len(len2.iterm) + len(len3.iterm) + len(len4.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.sterm, s4.sterm) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.sterm) : null);
  Object lenc34 = (c34.__cid == String() ? length(c34.sterm) : null);
  Object lenc12c34 = plus(lenc12.iterm, lenc34.iterm);
  assert arithmetize(xform(lenc12c34.iterm)) == len1234;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6)
void t2() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  Object len3 = (s3.__cid == String() ? length(s3.sterm) : null);
  Object len4 = (s4.__cid == String() ? length(s4.sterm) : null);
  Object len5 = (s5.__cid == String() ? length(s5.sterm) : null);
  Object len6 = (s6.__cid == String() ? length(s6.sterm) : null);
  int len123456 = len(len1.iterm) + len(len2.iterm) + len(len3.iterm) + len(len4.iterm) + len(len5.iterm) + len(len6.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.sterm, s4.sterm) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.sterm, s6.sterm) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.sterm) : null);
  Object lenc34 = (c34.__cid == String() ? length(c34.sterm) : null);
  Object lenc56 = (c56.__cid == String() ? length(c56.sterm) : null);
  Object lenc12c34c56 = plus(plus(lenc12.iterm,lenc34.iterm).iterm,lenc56.iterm);
  assert arithmetize(xform(lenc12c34c56.iterm)) == len123456;
}

// len(concat(s1,s2)) + len(concat(s3,s4)) + len(concat(s5,s6)) + len(concat(s7,s8)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5) + len(s6) + len(s7) + len(s8)
void t3() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object s6 = string();
  Object s7 = string();
  Object s8 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  Object len3 = (s3.__cid == String() ? length(s3.sterm) : null);
  Object len4 = (s4.__cid == String() ? length(s4.sterm) : null);
  Object len5 = (s5.__cid == String() ? length(s5.sterm) : null);
  Object len6 = (s6.__cid == String() ? length(s6.sterm) : null);
  Object len7 = (s7.__cid == String() ? length(s7.sterm) : null);
  Object len8 = (s8.__cid == String() ? length(s8.sterm) : null);
  int len12345678 = len(len1.iterm) + len(len2.iterm) + len(len3.iterm) + len(len4.iterm) + len(len5.iterm) + len(len6.iterm) + len(len7.iterm) + len(len8.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object c34 = (s3.__cid == String() ? concat(s3.sterm, s4.sterm) : null);
  Object c56 = (s5.__cid == String() ? concat(s5.sterm, s6.sterm) : null);
  Object c78 = (s7.__cid == String() ? concat(s7.sterm, s8.sterm) : null);
  Object lenc12 = (c12.__cid == String() ? length(c12.sterm) : null);
  Object lenc34 = (c34.__cid == String() ? length(c34.sterm) : null);
  Object lenc56 = (c56.__cid == String() ? length(c56.sterm) : null);
  Object lenc78 = (c78.__cid == String() ? length(c78.sterm) : null);
  Object lenc12c34c56c78 = plus(plus(lenc12.iterm,lenc34.iterm).iterm,plus(lenc56.iterm,lenc78.iterm).iterm);
  assert arithmetize(xform(lenc12c34c56c78.iterm)) == len12345678;
}

// len(concat(concat(s1,s2),s3) == len(s1) + len(s2) + len(s3)
void t4() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  Object len3 = (s3.__cid == String() ? length(s3.sterm) : null);
  int len123 = len(len1.iterm) + len(len2.iterm) + len(len3.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.sterm, s3.sterm) : null);
  Object lencc123 = (cc123.__cid == String() ? length(cc123.sterm) : null);
  assert arithmetize(xform(lencc123.iterm)) == len123;
}

// len(concat(concat(concat(s1,s2),s3),s4)) == len(s1) + len(s2) + len(s3) + len(s4)
void t5() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  Object len3 = (s3.__cid == String() ? length(s3.sterm) : null);
  Object len4 = (s4.__cid == String() ? length(s4.sterm) : null);
  int len1234 = len(len1.iterm) + len(len2.iterm) + len(len3.iterm) + len(len4.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.sterm, s3.sterm) : null);
  Object ccc1234 = (cc123.__cid == String() ? concat(cc123.sterm, s4.sterm) : null);
  Object lenccc1234 = (ccc1234.__cid == String() ? length(ccc1234.sterm) : null);
  assert arithmetize(xform(lenccc1234.iterm)) == len1234;
}

// len(concat(concat(concat(s1,s2),s3),concat(s4,s5)) == len(s1) + len(s2) + len(s3) + len(s4) + len(s5)
void t6() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object s4 = string();
  Object s5 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  Object len3 = (s3.__cid == String() ? length(s3.sterm) : null);
  Object len4 = (s4.__cid == String() ? length(s4.sterm) : null);
  Object len5 = (s5.__cid == String() ? length(s5.sterm) : null);
  int len12345 = len(len1.iterm) + len(len2.iterm) + len(len3.iterm) + len(len4.iterm) + len(len5.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object c45 = (s4.__cid == String() ? concat(s4.sterm, s5.sterm) : null);
  Object cc123 = (c12.__cid == String() ? concat(c12.sterm, s3.sterm) : null);
  Object ccc123c45 = (cc123.__cid == String() ? concat(cc123.sterm,c45.sterm) : null);
  Object lenccc123c45 = (ccc123c45.__cid == String() ? length(ccc123c45.sterm) : null);
  assert arithmetize(xform(lenccc123c45.iterm)) == len12345;
}

// len(concat(s1,concat(s1,concat(s1,concat(s1,s2))))) == len(s1) + len(s1) + len(s1) + len(s1) + len(s2)
void t7() {
  Object s1 = string();
  Object s2 = string();
  Object len1 = (s1.__cid == String() ? length(s1.sterm) : null);
  Object len2 = (s2.__cid == String() ? length(s2.sterm) : null);
  int len21111 = len(len2.iterm) + len(len1.iterm) + len(len1.iterm) + len(len1.iterm) + len(len1.iterm);
  Object c12 = (s1.__cid == String() ? concat(s1.sterm, s2.sterm) : null);
  Object c1c12 = (s1.__cid == String() ? concat(s1.sterm, c12.sterm) : null);
  Object c1c1c12 = (s1.__cid == String() ? concat(s1.sterm, c1c12.sterm) : null);
  Object c1c1c1c12 = (s1.__cid == String() ? concat(s1.sterm, c1c1c12.sterm) : null);
  Object lenc1c1c1c12 = (c1c1c1c12.__cid == String() ? length(c1c1c1c12.sterm) : null);
  assert arithmetize(xform(lenc1c1c1c12.iterm)) == len21111;
}

/*****************************************************************************/
/* len(replace) tests */
/*****************************************************************************/
// len(replace(s1,s2,s4)) == len(s1)
void t8() {
  Object s1 = string();
  Object s2 = string();
  Object s3 = string();
  Object ls1 = (s1.__cid == String() ? length(s1.sterm) : null);
  int len1 = len(ls1.iterm);
  Object r12 = (s1.__cid == String() ? replace(s1.sterm, s2.sterm, s3.sterm) : null);
  Object lenr12 = (r12.__cid == String() ? length(r12.sterm) : null);
  assert arithmetize(xform(lenr12.iterm)) == len1;
}
